# Site setings
name: "Brandon Byars"
description: "Brandon Byars's author site"
meta_description: "Site to promote Mayan Ruins"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl:
production_url: https://brandon-byars.com
#disqus: "justgoodthemes"
#mailchimp_url: "//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117"
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics:

# Author
author:
  name: "Brandon Byars"
  image: "authorimage.jpg"
  greetings: "Hi there!"
  description: "My name is Brandon Byars."
  bio: "Brandon's bio"

# Contact form setings
email: youremail@email.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
github: bbyars
email: brandon.byars+author@gmail.com

# Navigation
navigation:
  - text: About
    url: /about
  - text: Archive
    url: /tags
  - text: Style Guide
    url: /style-guide

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
